### ISSUE TITLE
Issues and tidy-up To-do's

### ISSUE THREAD

**Issue by ajwalks** [joomla-projects/gsoc16_recording-action-logs#33]
Using this Issue to log bugs etc found during testing.

**Comment by ajwalks** [comment]
1) Please try to keep naming consistent with letters and words. In the System Plugin its called "System - User actions Log " and in the menu its called "User Actions log".  Other native extensions tend to use capitals for each word, eg: "User Actions Log".
2) I installed latest package and got a white screen (when visiting the Component on Joomla 3.5.1). When I ran Joomla updator to 3.6.0 the component ran without error. Please check this to note the issue.
3) Plugin had "0" in the number of days to delete logs. Does this mean no deleting will take place or will it literally delete it in a 24hour period? Should this be a default of one month perhaps?
4) I enabled IP logging in Plugin, however under the "IP Address" column I only get number "1" displayed.
5) In the Component, the select a user search box button is not clear how to use. Can this just be a button rather than the search box?
6) Export Button seems to export all entries? I filtered my view to a particular extension only, then selected it and hit export, but got all entries. Is this how it should work?
7) After attempting to export some entries, when I continued to use Search Filters the selection of them would activate a new download popup.
8) Trying to delete a selection of logs causes an error on a 2nd screen:
"An error has occurred. 0 Table Userlogs not supported. File not found. " . The button on that page takes you back to the control panel
9) The editing of an existing Module does not get a log, nor does the creation of a new Module (I tried to create breadcrumbs module).
10) Updating Joomla from 3.6.0 to 3.6.2 did not store a log
11) Creating new user group did not store a log, but creating a new level access did.
12) Changing Template did not store a log
13) Setting Content as Featured did not store a log
14) Changing Global Configurations did not store a log
15) Sending Mass Mail did not store a log

Hope this feedback helps.

**Comment by muhakh** [comment]
Thank you @ajwalks for your feedback. I'll work on these issues and push them back as soon as I fix them.

**Comment by Llewellynvdm** [comment]
## During Install
- The package installed without errors on Joomla 3.6.2
- Had a nice success message
- This may not be needed if it becomes part of the Joomla core

## Plugin View
- Was not autamaticly published, we could add a note in install message to activate manualy.
- Has a nice list of events to select, ther would need to be documentation on how 3rd party devs can add events here from there components.
- To log IPs is available and by default set to no, good.

## Component View
- Has three top buttons, delete, Export as CSV, Undo
- The undo feature may need to be removed for now... so we can focus on basic and documentation to be completed
- **Bug** Strict standards: Only variables should be passed by reference in /plugins/system/userlogs/userlogs.php on line 310
- Extension name not translated
- Log install of extention, but if extention install fails it does not show that.. just drops the extentsion_id (would like to know that it failed)
- _Extension installed, its id="10004"_ is what will show if instal was successful, can't we load the extention name instead.
- When deleting a log **Table Userlogs not supported. File not found** error comes up.

Lets look at these including what Al mentioned, since I found the same issues.

**Comment by muhakh** [comment]
Thank you @Llewellynvdm for your feedback. This is the work of yesterday and an hour today :D to solve most of the problems. https://drive.google.com/file/d/0BwmAXJEKZjMlY0tKX0xVLVNLR3c/

#### These are the problems that are solved:
- Naming became more consistent.
- I think the white screen issue with previous version is solved.
- For the plugin having "0" in the number of days to delete logs, this means no deleting at all. Having a default value of 30 days is not a problem at all. It's just changing 0 to 30.
- The IP log has value of 1, this is because of the localhost. In production it will be different.
- I added another export button to export selected logs and the old one became export all logs.
- The delete error is solved (didn't add the tables folder to the .XML manifest)
- Added logging for modules, templates & new user group.
- I removed the undo button

I can't find events corresponding to **Joomla update, mass mail, global configurations or making articles featured**. If any one can help me with this, it would be really appreciated.

I'll work on the download popup that appears after extracting and using Search Filters and the extensions issues that @Llewellynvdm mentioned.
I'll work also on something I found that after using the search filters it isn't kept opened.

Thank you again for your feedback and I'm waiting for more.

**Comment by ajwalks** [comment]
Further testing of latest version:
1) IP Number Still not showing?.. maybe because I’m on local copy?
2) Filters: Plese insert a placeholder text for the EXTENSION filter type. 
3) Plugin title still has small letter “A” for word Actions. Please make uppercase to match all other references of the extension.
4) When I upload an image, I get this for the MESSAGE Log: - {"title":"","isNew":"true", "event":"onContentAfterSave", "id":} 
5) I added a User Note and it logged it as a NEW USER being created ?
6) I ran an AUTO UPDATE on an extension that Joomla said was available. It logged this “Extension deleted, its id="28" “ but did not log anything as being updated ?
7) Kinda like the above, upgrading from Joomla 3.6.0 to 3.6.2 did not register any update logs. 
8) FYI: Global Check-in, Mass Mail, Featured Article Toggle, Changing Template, Deleting Cache did not register any logs.
9) I unpublished a plugin, and it logged the event,.. but had word "Plugin was unpublished" with no Plugin ID or title name.. so not helpful to know what plugin the action was generated from?
10) Creating a redirect logged an entry, but it contained no title. Creating a new tag did have a title.
11) Is it possible to "AUTOMATE" an action where a script creates new articles and we can test how efficient the entries are. eg: if you have the plugin value set to be a year before deletion, what size could this grow a database to and is it efficient as can be?

Will post back more as I find them. Please send updated version through when you have done more work on these.
